# Generated by Django 3.2.9 on 2022-01-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220121_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='posterPath',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
